(function(){
  const style=document.createElement("link");style.rel="stylesheet";style.href="achievements.css";document.head.appendChild(style);const statusStyle=document.createElement("link");statusStyle.rel="stylesheet";statusStyle.href="status.css";document.head.appendChild(statusStyle);
  const characters={
    1:{name:"さきうさ",src:"assets/sakiusa-complete.gif",still:"assets/sakiusa-complete-still.png",lines:["やったね、ぜんぶ正解でおじゃ！","見事なパーフェクトでおじゃ！","がんばりが花ひらいたね！","ぜんぶ覚えたなんて、すごい！","さきうさも胸がいっぱい！","今日のきみは満点名人！","一問ずつの努力が実ったね！","すてきな集中力でおじゃ！","この調子で次もいこう！","ぴかぴかの100点、おめでとう！"]},
    2:{name:"軍師うさぎ",src:"assets/sakiusa-idle-strategist.gif",still:"assets/sakiusa-correct-strategist.png",lines:["二度の完全勝利、見事な策です！","知識の陣が整いましたぞ！","全問二勝、軍師も感服です！","復習の作戦、大成功です！","弱点なき布陣になりました！","努力を重ねた見事な勝利！","覚える力、まことにあっぱれ！","この調子なら次の戦も安心！","一問も逃さぬ集中力です！","二周の鍛錬、しかと見届けました！"]},
    3:{name:"姫うさぎ",src:"assets/sakiusa-idle-princess.gif",still:"assets/sakiusa-correct-princess.png",lines:["三度の満点、とても素敵です！","努力がきらきら輝いています！","すべて三回正解、お見事です！","今日のあなたは満点の星！","ていねいな復習が実りましたね！","姫も思わず拍手しています！","覚えた言葉が宝物になりました！","素晴らしいがんばりですわ！","もう立派な言葉の達人ですね！","三つの花丸を贈ります！"]},
    4:{name:"卑弥呼うさぎ",src:"assets/sakiusa-idle-himiko.gif",still:"assets/sakiusa-correct-himiko.png",lines:["四度の完全制覇、天晴れです！","知識の光が満ちています！","全問四勝、伝説の学び手です！","ここまで続けた力が宝です！","卑弥呼も大いに喜んでいます！","揺るがぬ知識になりましたね！","努力の積み重ね、まことに見事！","言葉を自在に操る達人です！","最高位の花丸を授けます！","四周完全、堂々たる大記録です！"]}
  };
  const nextNames={1:"軍師うさぎ",2:"姫うさぎ",3:"卑弥呼うさぎ"};
  function state(testId){const qs=data.questions.filter(q=>q.testId===testId);if(!qs.length)return{level:0,min:0};const counts=qs.map(q=>data.results.filter(r=>r.qid===q.id&&r.good).length),min=Math.min(...counts);return{level:Math.min(min,4),min,counts}}
  function hash(s){return[...s].reduce((a,c)=>(a*31+c.charCodeAt(0))>>>0,7)}
  function line(testId,s){const c=characters[s.level];return c.lines[(hash(testId)+s.min)%c.lines.length]}
  function nextText(s){return s.level<4?`あと1回、全問題に正解すると「${nextNames[s.level]}」へ！`:"最高階級を達成！ これからも記録を伸ばそう！"}
  function hero(testId){const s=state(testId),c=characters[s.level];if(!c)return`<div class="hero-mastery pending"><span>あと少し！</span><small>まだ正解していない問題があります</small></div>`;return`<div class="hero-mastery"><div class="rabbit-talk"><b>${esc(line(testId,s))}</b><small>${esc(nextText(s))}</small></div><img src="${c.still}" alt="${c.name}が喜ぶ様子"></div>`}
  function compact(t){const s=state(t.id),past=t.date<today(),label=past?"もう一度テスト":"この範囲をテスト";return`${s.min?`<div class="compact-perfect"><span class="hanamaru">💮</span><div><b>パーフェクト ${s.min}回！</b><small>${s.level<4?`次の階級まで あと1回`:"最高階級！"}</small></div></div>`:`<div class="compact-perfect not-yet"><span>あと少し</span><small>まずは全問正解をめざそう</small></div>`}<button class="tiny compact-test" data-achievement-test="${esc(t.id)}">${label}</button>`}
  const baseTests=tests;tests=function(subject){return baseTests(subject).sort((a,b)=>{const ap=a.date<today(),bp=b.date<today();return ap!==bp?ap-bp:ap?b.date.localeCompare(a.date):a.date.localeCompare(b.date)})};
  const originalRenderHome=renderHome;
  renderHome=function(){originalRenderHome();document.querySelectorAll("#testCards .test-card").forEach((card,i)=>{const t=tests()[i];if(t){card.classList.add("test-card-compact");if(t.date<today())card.classList.add("past-test");card.insertAdjacentHTML("beforeend",compact(t))}});document.querySelectorAll("#parentTestCards .test-card").forEach((card,i)=>{const t=tests()[i];if(t){card.classList.add("test-card-compact");if(t.date<today())card.classList.add("past-test");card.insertAdjacentHTML("beforeend",compact(t))}});document.querySelectorAll("#nextCards .card").forEach((card,i)=>{const t=nextTest(i===0?"英単語":"漢字");if(t){card.classList.add("hero-with-rabbit");card.insertAdjacentHTML("beforeend",hero(t.id))}});document.querySelectorAll("[data-achievement-test]").forEach(b=>b.onclick=()=>{const t=tests().find(x=>x.id===b.dataset.achievementTest);if(!t)return;$("subject").value=t.subject;renderChecks();show("quiz");setTimeout(()=>{const c=document.querySelector(`[data-check="${CSS.escape(t.id)}"]`);if(c)c.checked=true},0)})};
  const originalFinish=finish;
  finish=function(early){originalFinish(early);if(early)return;const ids=[...new Set(session.queue.map(id=>data.questions.find(q=>q.id===id)?.testId).filter(Boolean))],best=ids.map(id=>({id,...state(id)})).sort((a,b)=>b.level-a.level)[0];if(best?.level){const c=characters[best.level];$("mascot").src=c.src;$("finish").insertAdjacentHTML("afterbegin",`<div class="achievement-large"><div class="rabbit-talk"><h2>${esc(line(best.id,best))}</h2><p>${esc(nextText(best))}</p></div><img src="${c.src}" alt="${c.name}が喜ぶ様子"></div>`)}};
  render();
})();
