(function(){
if(!document.body.classList.contains("parent-site"))return;
const css=document.createElement("link");css.rel="stylesheet";css.href="admin-tools.css";document.head.appendChild(css);
let selected=new Set(),sortOrder="newest";
const clean=v=>String(v??"").normalize("NFKC").toLowerCase().replace(/[\s　]+/g,"").replace(/[（）()＿_・,，。．'’"“”]/g,"");
function questionKey(q){const base=`${q.date}|${clean(q.subject)}`;return q.no!==undefined&&String(q.no).trim()!==""?`${base}|no:${clean(q.no)}`:`${base}|qa:${clean(q.prompt)}|${clean(q.answer)}`}
function stamp(q){if(q.updatedAt)return new Date(q.updatedAt).getTime()||0;if(q.createdAt)return new Date(q.createdAt).getTime()||0;const m=String(q.id).match(/^q-(\d{13})/);return m?Number(m[1]):new Date(q.date+"T00:00:00").getTime()||0}
function mergeInto(keep,old){["explanation","note","title","range"].forEach(k=>{if(!keep[k]&&old[k])keep[k]=old[k]});if((!keep.wrong||!keep.wrong.length)&&old.wrong?.length)keep.wrong=old.wrong}
function dedupeCore(){const ordered=[...data.questions].sort((a,b)=>stamp(b)-stamp(a)),seen=new Map(),remove=new Map;for(const q of ordered){const key=questionKey(q);if(seen.has(key)){const keep=seen.get(key);mergeInto(keep,q);remove.set(q.id,keep.id)}else seen.set(key,q)}if(!remove.size)return 0;data.results.forEach(r=>{if(remove.has(r.qid))r.qid=remove.get(r.qid)});if(data.favorites)data.favorites=[...new Set(data.favorites.map(id=>remove.get(id)||id))];data.questions=data.questions.filter(q=>!remove.has(q.id));selected=new Set([...selected].filter(id=>!remove.has(id)));return remove.size}
if(!data.adminDateMigrationV1){const fixes={"2026-07-06":"2026-07-07","2026-07-09":"2026-07-10"};data.questions.forEach(q=>{if(fixes[q.date]&&(q.range==="No.500〜550"||q.range==="第12回")){q.date=fixes[q.date];q.testId=`${q.date}-${q.subject}`}});data.adminDateMigrationV1=true;localStorage.setItem(KEY,JSON.stringify(data))}
function fmtStamp(q){const s=stamp(q);return s?new Date(s).toLocaleString("ja-JP",{year:"numeric",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}):"－"}
function renderAdmin(){const body=$("questions"),table=body.closest("table"),wrap=table.parentElement;if(!$("adminBulk"))wrap.insertAdjacentHTML("beforebegin",'<div id="adminBulk" class="admin-bulk"><label><input id="selectAllQuestions" type="checkbox"> すべて選択</label><button id="bulkDelete" class="secondary">選択した問題を削除</button><button id="dedupeQuestions" class="secondary">重複を一括整理</button><label>並び順<select id="questionSort"><option value="newest">更新日の新しい順</option><option value="oldest">更新日の古い順</option><option value="testDate">テスト日の近い順</option></select></label><span id="selectedStatus">0件選択</span></div>');
 table.querySelector("thead").innerHTML='<tr><th>選択</th><th>更新日</th><th>テスト日</th><th>科目</th><th>No.</th><th>範囲</th><th>問題</th><th>解答</th><th>成績</th><th>操作</th></tr>';
 let qs=[...data.questions];qs.sort((a,b)=>sortOrder==="oldest"?stamp(a)-stamp(b):sortOrder==="testDate"?a.date.localeCompare(b.date)||String(a.no).localeCompare(String(b.no),"ja",{numeric:true}):stamp(b)-stamp(a));
 body.innerHTML=qs.map(q=>`<tr><td><input type="checkbox" data-select-question="${esc(q.id)}" ${selected.has(q.id)?"checked":""}></td><td class="update-date">${fmtStamp(q)}</td><td>${fd(q.date)}</td><td>${esc(q.subject)}</td><td>${esc(q.no)}</td><td>${esc(q.range)}</td><td class="question-cell">${esc(q.prompt)}</td><td><b>${esc(q.answer)}</b></td><td>${qStats(q)}</td><td><button class="tiny" data-admin-edit="${q.id}">編集</button> <button class="tiny danger" data-admin-delete="${q.id}">削除</button></td></tr>`).join("");
 const status=()=>{$("selectedStatus").textContent=`${selected.size}件選択`};document.querySelectorAll("[data-select-question]").forEach(c=>c.onchange=()=>{c.checked?selected.add(c.dataset.selectQuestion):selected.delete(c.dataset.selectQuestion);status()});$("selectAllQuestions").onchange=e=>{selected=e.target.checked?new Set(qs.map(q=>q.id)):new Set;renderAdmin()};$("questionSort").value=sortOrder;$("questionSort").onchange=e=>{sortOrder=e.target.value;renderAdmin()};$("bulkDelete").onclick=()=>{if(!selected.size)return alert("削除する問題を選択してください。");if(!confirm(`${selected.size}問を削除しますか？`))return;data.questions=data.questions.filter(q=>!selected.has(q.id));data.results=data.results.filter(r=>!selected.has(r.qid));if(data.favorites)data.favorites=data.favorites.filter(id=>!selected.has(id));selected.clear();save()};$("dedupeQuestions").onclick=()=>{const n=dedupeCore();localStorage.setItem(KEY,JSON.stringify(data));render();alert(n?`${n}件の重複を整理しました。成績とお気に入りは残しています。`:"重複は見つかりませんでした。")};document.querySelectorAll("[data-admin-edit]").forEach(b=>b.onclick=()=>editQuestion(b.dataset.adminEdit));document.querySelectorAll("[data-admin-delete]").forEach(b=>b.onclick=()=>{if(confirm("この問題を削除しますか？")){selected=new Set([b.dataset.adminDelete]);$("bulkDelete").click()}});status()}
renderManage=renderAdmin;
async function rowsFromFile(file){const csv=file.name.endsWith(".csv"),wb=XLSX.read(csv?await file.text():await file.arrayBuffer(),{type:csv?"string":"array",cellDates:true}),names=csv?[wb.SheetNames[0]]:wb.SheetNames.filter(n=>/^問題入力(?:$|[_＿‗\-].*)/.test(n));return names.flatMap(name=>XLSX.utils.sheet_to_json(wb.Sheets[name],{defval:""}))}
function rowDate(v){return v instanceof Date?localYmd(v):String(v).slice(0,10)}
function spellWarnings(row){const text=`${row["問題"]||""} ${row["解答"]||""}`,rules=[[/(^|\s)1 know\b/i,"1 know → I know"],[/\bThay\b/i,"Thay → They"],[/\bIt'S\b/,"It'S → It's"],[/\bIf rained\b/i,"If rained → It rained"],[/\bnowaday\b/i,"nowaday → nowadays"],[/\bprinciple's\b/i,"principle's → principles"]];return rules.filter(([r])=>r.test(text)).map(([,m])=>`No.${row["No"]||"?"} ${m}`)}
const oldImport=importSheet;importSheet=async function(file){const before=new Set(data.questions.map(q=>q.id)),rows=await rowsFromFile(file);await oldImport(file);const now=new Date().toISOString(),warnings=[],beforeKeys=new Set([...before]);let updated=0;for(const r of rows){const date=rowDate(r["テスト日"]||r["出題テスト日"]),subject=String(r["科目"]||""),no=String(r["No"]||r["No."]||"");if(!date||!subject||!no||!r["問題"]||!r["解答"])continue;const key=questionKey({date,subject,no,prompt:r["問題"],answer:r["解答"]}),q=[...data.questions].sort((a,b)=>stamp(b)-stamp(a)).find(x=>questionKey(x)===key);if(!q)continue;if(beforeKeys.has(q.id))updated++;q.testId=`${date}-${subject}`;q.date=date;q.subject=subject;q.no=no;q.title=japaneseGlyphs(String(r["テスト名"]||`${subject}ミニテスト`));q.range=japaneseGlyphs(String(r["範囲"]||""));q.prompt=japaneseGlyphs(String(r["問題"]));q.answer=String(r["解答"]);q.explanation=japaneseGlyphs(String(r["解説"]||"").trim()||autoExplanation(subject,q.prompt,q.answer));q.wrong=[r["誤答候補1"],r["誤答候補2"],r["誤答候補3"]].filter(Boolean).map(String);q.note=japaneseGlyphs(String(r["管理用備考欄"]||r["備考"]||""));q.createdAt=q.createdAt||now;q.updatedAt=now;warnings.push(...spellWarnings(r))}data.questions.filter(q=>!before.has(q.id)).forEach(q=>{q.createdAt=q.createdAt||now;q.updatedAt=now});const n=dedupeCore();data.importNotices=data.importNotices||[];if(updated)data.importNotices.unshift({at:now,text:`試験問題更新：${updated}問をExcelから上書き`});if(warnings.length)data.importNotices.unshift({at:now,text:`スペル確認：${warnings.length}件の候補あり（${warnings.slice(0,2).join("、")}）`});data.importNotices=data.importNotices.slice(0,20);localStorage.setItem(KEY,JSON.stringify(data));render();$("importMessage").textContent+=` 上書き更新：${updated}問。${n?` 重複整理：${n}問。`:""}${warnings.length?` スペル確認候補：${warnings.join("／")}`:" スペル確認候補なし。"}`};
const oldSubmit=$("editor").onsubmit;$("editor").onsubmit=e=>{const id=$("editId").value,old=id?data.questions.find(q=>q.id===id):null,created=old?.createdAt;oldSubmit(e);const saved=id?data.questions.find(q=>q.id===id):data.questions.reduce((a,b)=>stamp(a)>stamp(b)?a:b);if(saved){saved.createdAt=created||saved.createdAt||new Date().toISOString();saved.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(data));renderAdmin()}};
renderAdmin();
$("editPrompt").spellcheck=true;$("editAnswer").spellcheck=true;$("editExplanation").spellcheck=true;
})();
