(async function(){
const config={projectId:"sakiusa-weekly-test",appId:"1:256821715037:web:5b4bb806b86ed451222db4",storageBucket:"sakiusa-weekly-test.firebasestorage.app",apiKey:"AIzaSyDM7_uiFD7iDNigwvP3Q7UT9d25cXApoSQ",authDomain:"sakiusa-weekly-test.firebaseapp.com",messagingSenderId:"256821715037"};
const [{initializeApp},{getFirestore,doc,setDoc,getDoc,getDocs,collection,onSnapshot,writeBatch}]=await Promise.all([import("https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js"),import("https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js")]);
const db=getFirestore(initializeApp(config)),CODE_KEY="sakiusa-family-code",parent=document.body.classList.contains("parent-site");let code=localStorage.getItem(CODE_KEY)||"",ready=false,busy=false,qCache=new Map,rCache=new Map,stateCache="";
const safe=x=>JSON.parse(JSON.stringify(x)),state=()=>({favorites:data.favorites||[],profileRank:data.profileRank||0,profileStreak:data.profileStreak||0,lastLoginDay:data.lastLoginDay||"",importNotices:data.importNotices||[],updatedAt:new Date().toISOString()}),stateJson=()=>JSON.stringify({...state(),updatedAt:""});
function modal(html){let m=document.getElementById("cloudModal");if(!m){m=document.createElement("div");m.id="cloudModal";m.innerHTML='<div class="cloud-box"><div id="cloudContent"></div></div>';document.body.appendChild(m)}document.getElementById("cloudContent").innerHTML=html;m.hidden=false;return m}
function closeModal(){const m=document.getElementById("cloudModal");if(m)m.hidden=true}
function randomCode(){const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789",a=new Uint32Array(12);crypto.getRandomValues(a);return[...a].map(n=>chars[n%chars.length]).join("")}
async function hashPin(pin){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(`${code}:${pin}`));return[...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function syncBadge(text,ok=true){let b=document.getElementById("cloudBadge");if(!b){b=document.createElement("button");b.id="cloudBadge";b.className="cloud-badge";document.querySelector("nav").appendChild(b);b.onclick=showSettings}b.textContent=`${ok?"☁":"⚠"} ${text}`;b.classList.toggle("offline",!ok)}
async function commitOps(ops){for(let i=0;i<ops.length;i+=400){const batch=writeBatch(db);ops.slice(i,i+400).forEach(o=>o.del?batch.delete(o.ref):batch.set(o.ref,o.value));await batch.commit()}}
async function syncLocal(){if(!ready||busy)return;busy=true;try{const ops=[],localQ=new Map(data.questions.map(q=>[String(q.id),JSON.stringify(q)])),localR=new Map(data.results.map(r=>[String(r.id),JSON.stringify(r)]));for(const[id,j]of localQ)if(qCache.get(id)!==j)ops.push({ref:doc(db,"families",code,"questions",id),value:safe(JSON.parse(j))});for(const id of qCache.keys())if(!localQ.has(id))ops.push({ref:doc(db,"families",code,"questions",id),del:true});for(const[id,j]of localR)if(rCache.get(id)!==j)ops.push({ref:doc(db,"families",code,"results",id),value:safe(JSON.parse(j))});for(const id of rCache.keys())if(!localR.has(id))ops.push({ref:doc(db,"families",code,"results",id),del:true});const sj=stateJson();if(sj!==stateCache)ops.push({ref:doc(db,"families",code,"state","current"),value:state()});if(ops.length)await commitOps(ops);syncBadge("同期済み")}catch(e){console.error(e);syncBadge("オフライン",false)}finally{busy=false}}
function applyRemoteQuestions(snap){qCache=new Map(snap.docs.map(d=>[d.id,JSON.stringify(d.data())]));data.questions=snap.docs.map(d=>d.data());persistRemote()}
function applyRemoteResults(snap){rCache=new Map(snap.docs.map(d=>[d.id,JSON.stringify(d.data())]));data.results=snap.docs.map(d=>d.data());persistRemote()}
function applyRemoteState(s){if(!s.exists())return;const x=s.data();stateCache=JSON.stringify({...x,updatedAt:""});data.favorites=x.favorites||[];data.profileRank=x.profileRank||0;data.profileStreak=x.profileStreak||0;data.lastLoginDay=x.lastLoginDay||data.lastLoginDay;data.importNotices=x.importNotices||[];persistRemote()}
let renderTimer;function persistRemote(){localStorage.setItem(KEY,JSON.stringify(data));clearTimeout(renderTimer);renderTimer=setTimeout(()=>{try{render()}catch{}},80)}
async function startListeners(){onSnapshot(collection(db,"families",code,"questions"),applyRemoteQuestions,e=>syncBadge("同期エラー",false));onSnapshot(collection(db,"families",code,"results"),applyRemoteResults,e=>syncBadge("同期エラー",false));onSnapshot(doc(db,"families",code,"state","current"),applyRemoteState,e=>syncBadge("同期エラー",false));ready=true;syncBadge("同期済み");setInterval(syncLocal,1500)}
async function connectFamily(){syncBadge("接続中");const meta=await getDoc(doc(db,"families",code));if(!meta.exists())throw Error("家族コードが見つかりません");if(parent&&!sessionStorage.getItem("sakiusa-parent-unlocked")){return askPin(meta.data().pinHash)}const [qs,rs,st]=await Promise.all([getDocs(collection(db,"families",code,"questions")),getDocs(collection(db,"families",code,"results")),getDoc(doc(db,"families",code,"state","current"))]);if(qs.empty){ready=true;await syncLocal();ready=false}else{qCache=new Map(qs.docs.map(d=>[d.id,JSON.stringify(d.data())]));data.questions=qs.docs.map(d=>d.data())}if(!rs.empty){rCache=new Map(rs.docs.map(d=>[d.id,JSON.stringify(d.data())]));data.results=rs.docs.map(d=>d.data())}if(st.exists())applyRemoteState(st);persistRemote();await startListeners()}
function askPin(pinHash){modal(`<h2>保護者PIN</h2><p>保護者画面を開くPINを入力してください。</p><input id="cloudPin" type="password" inputmode="numeric" maxlength="8" placeholder="PIN"><p id="cloudError"></p><button id="unlockCloud" class="primary">開く</button>`);document.getElementById("unlockCloud").onclick=async()=>{if(await hashPin(document.getElementById("cloudPin").value)!==pinHash)return document.getElementById("cloudError").textContent="PINが違います。";sessionStorage.setItem("sakiusa-parent-unlocked","1");closeModal();connectFamily()}}
async function createFamily(pin){code=randomCode();localStorage.setItem(CODE_KEY,code);await setDoc(doc(db,"families",code),{pinHash:await hashPin(pin),createdAt:new Date().toISOString()});ready=true;await syncLocal();ready=false;sessionStorage.setItem("sakiusa-parent-unlocked","1");closeModal();await startListeners();showCode()}
function firstSetup(){if(parent)modal('<h2>クラウド同期を開始</h2><p>4～8桁の保護者PINを決めてください。</p><input id="newPin" type="password" inputmode="numeric" maxlength="8" placeholder="PIN"><p id="cloudError"></p><button id="createFamily" class="primary">家族コードを作成</button>'),document.getElementById("createFamily").onclick=()=>{const p=document.getElementById("newPin").value;if(!/^\d{4,8}$/.test(p))return document.getElementById("cloudError").textContent="数字4～8桁で入力してください。";createFamily(p)};else modal('<h2>家族データへ接続</h2><p>保護者画面に表示された12文字の家族コードを入力してください。</p><input id="familyCode" maxlength="12" placeholder="家族コード"><p id="cloudError"></p><button id="joinFamily" class="primary">接続</button>'),document.getElementById("joinFamily").onclick=()=>{const c=document.getElementById("familyCode").value.toUpperCase().replace(/\s/g,"");if(!/^[A-Z2-9]{12}$/.test(c))return document.getElementById("cloudError").textContent="12文字のコードを入力してください。";code=c;localStorage.setItem(CODE_KEY,code);closeModal();connectFamily().catch(e=>{localStorage.removeItem(CODE_KEY);code="";document.getElementById("cloudError").textContent=e.message;firstSetup()})}}
function showCode(){modal(`<h2>同期設定</h2><p>子どもの端末に次の家族コードを入力してください。</p><div class="family-code">${code}</div><p>保護者画面は設定したPINで保護されます。</p><button id="closeCloud" class="secondary">閉じる</button>`);document.getElementById("closeCloud").onclick=closeModal}
function showSettings(){if(code)showCode();else firstSetup()}
const style=document.createElement("style");style.textContent='#cloudModal{position:fixed;inset:0;z-index:999;background:#3a3340aa;display:grid;place-items:center;padding:18px}#cloudModal[hidden]{display:none}.cloud-box{width:min(480px,100%);background:white;border-radius:22px;padding:25px;box-shadow:0 20px 60px #0005}.cloud-box input{width:100%;font:inherit;padding:13px;border:2px solid #eadde4;border-radius:12px;margin:8px 0}.family-code{font-size:2rem;font-weight:900;letter-spacing:.15em;text-align:center;background:#fff7d6;padding:16px;border-radius:14px}.cloud-badge{border:0;background:#edf8f1;color:#237947;border-radius:99px;padding:8px 11px;font-weight:800;cursor:pointer}.cloud-badge.offline{background:#fff0e5;color:#a55320}#cloudError{color:#b13a3a;font-weight:800}';document.head.appendChild(style);
if(code)connectFamily().catch(e=>{console.error(e);syncBadge("未接続",false);firstSetup()});else firstSetup();
})();
