(function(){
const css=document.createElement("link");css.rel="stylesheet";css.href="final-tweaks.css";document.head.appendChild(css);
const latest=qid=>[...data.results].reverse().find(r=>r.qid===qid);
if(document.body.classList.contains("child-site")){
 statsFor=function(qs){const total=qs.length,correct=qs.filter(q=>latest(q.id)?.good).length;return{correct,total,rate:total?Math.round(correct/total*100):null}};
 const limit=$("limit");if(![...limit.options].some(o=>o.value==="unfinished")){limit.add(new Option("未完了分（0件）","unfinished"));limit.add(new Option("間違えた分（0件）","wrongNow"))}
 function chosen(){const ids=[...document.querySelectorAll("[data-check]:checked")].map(x=>x.dataset.check);return data.questions.filter(q=>q.subject===$("subject").value&&ids.includes(q.testId))}
 const runCount=q=>data.results.filter(r=>r.qid===q.id).length;function unfinishedQuestions(qs){const target=Math.max(1,...qs.map(runCount));return qs.filter(q=>runCount(q)<target)}
 function updateTrainingCounts(){const qs=chosen(),unfinished=unfinishedQuestions(qs).length,wrong=qs.filter(q=>latest(q.id)&&!latest(q.id).good).length;$("selectedCount").textContent=`問題：現在 ${qs.length}問選択中（未完了${unfinished}件／誤答${wrong}件）`;limit.querySelector('[value="unfinished"]').textContent=`未完了分（${unfinished}件）`;limit.querySelector('[value="wrongNow"]').textContent=`間違えた分（${wrong}件）`}
 $("testChecks").addEventListener("change",updateTrainingCounts);$("subject").addEventListener("change",()=>setTimeout(updateTrainingCounts));new MutationObserver(()=>setTimeout(updateTrainingCounts,0)).observe($("testChecks"),{childList:true,subtree:true});document.addEventListener("click",()=>setTimeout(updateTrainingCounts,80),true);
 $("start").onclick=()=>{const subject=$("subject").value,ids=[...document.querySelectorAll("[data-check]:checked")].map(x=>x.dataset.check);if(!ids.length)return alert("テスト予定日を1つ以上選んでください。");let qs=data.questions.filter(q=>q.subject===subject&&ids.includes(q.testId)),mode=$("mode").value,lim=limit.value;if(mode==="everWrong")qs=qs.filter(q=>data.results.some(r=>r.qid===q.id&&!r.good));if(mode==="latestWrong"){const last=[...data.results].reverse().find(r=>r.subject===subject),bad=new Set(last?data.results.filter(r=>r.attempt===last.attempt&&!r.good).map(r=>r.qid):[]);qs=qs.filter(q=>bad.has(q.id))}if(lim==="unfinished")qs=unfinishedQuestions(qs);else if(lim==="wrongNow")qs=qs.filter(q=>latest(q.id)&&!latest(q.id).good);if(!qs.length)return alert("この条件で出題できる問題がありません。");qs.sort((a,b)=>{const x=priority(a),y=priority(b);return x[0]-y[0]||x[1]-y[1]||x[2]-y[2]});if(lim!=="all"&&lim!=="unfinished"&&lim!=="wrongNow")qs=qs.slice(0,Number(lim));session={id:`a-${Date.now()}`,subject,queue:qs.map(q=>q.id),index:0,records:[],started:0,pendingRetry:[]};$("setup").hidden=true;$("finish").hidden=true;$("question").hidden=false;ask()};
 function preset(t,kind="unfinished"){$("subject").value=t.subject;renderChecks();show("quiz");setTimeout(()=>{const c=document.querySelector(`[data-check="${CSS.escape(t.id)}"]`);if(c)c.checked=true;$("mode").value="understanding";limit.value=kind;updateTrainingCounts()},0)}
 function enhanceChild(){updateTrainingCounts();const soon=tests().filter(t=>{const d=Math.ceil((new Date(t.date+"T00:00:00")-new Date(today()+"T00:00:00"))/864e5);return d>=0&&d<=3}),list=$("todoList");list.innerHTML="";soon.forEach((t,i)=>{const qs=data.questions.filter(q=>q.testId===t.id),unfinished=unfinishedQuestions(qs).length,wrong=qs.filter(q=>latest(q.id)&&!latest(q.id).good).length,b=document.createElement("button");b.dataset.extraTodo=i;if(unfinished||wrong){b.textContent=`▶ ${fd(t.date)} ${t.title}：未完了${unfinished}問／誤答${wrong}問`;b.onclick=()=>preset(t,unfinished?"unfinished":"wrongNow")}else if(qs.length){const min=Math.min(...qs.map(q=>data.results.filter(r=>r.qid===q.id&&r.good).length));b.textContent=`☆ ${fd(t.date)} ${t.title}：${min+1}回目のパーフェクトに挑戦`;b.onclick=()=>preset(t,"all")}list.appendChild(b)});if(!soon.length)list.innerHTML="<p>3日以内のテストはありません。</p>"}
 const prevRender=render;render=function(){prevRender();enhanceChild()};
 function enhanceQuick(){const list=$("battleList");if(!list)return;list.querySelectorAll(".older-battles-toggle").forEach(x=>x.remove());const todayText=new Date().toLocaleDateString("ja-JP"),older=[];list.querySelectorAll("details.battle").forEach(d=>{if(!d.querySelector("summary").textContent.startsWith(todayText)){d.classList.add("older-battle");d.hidden=true;older.push(d)}});if(older.length){const b=document.createElement("button");b.className="secondary older-battles-toggle";b.textContent=`昨日以前の戦歴を見る（${older.length}件）`;b.onclick=()=>{const open=older[0].hidden;older.forEach(x=>x.hidden=!open);b.textContent=open?"昨日以前の戦歴を閉じる":`昨日以前の戦歴を見る（${older.length}件）`};list.prepend(b)}}
 $("childNav").querySelector('[data-view="quick"]')?.addEventListener("click",()=>setTimeout(enhanceQuick,0));enhanceChild();render();
}
if(document.body.classList.contains("parent-site")){
 function enhanceParentResults(){document.querySelectorAll(".result-detail table").forEach(table=>{const heads=table.querySelectorAll("th");if(heads[1])heads[1].textContent="テスト予定日";table.querySelectorAll("tr").forEach(row=>row.children[4]?.remove())});document.querySelectorAll(".parent-result-card").forEach(card=>{const id=card.querySelector("[data-toggle-test]")?.dataset.toggleTest;if(!id)return;const qs=data.questions.filter(q=>q.testId===id),done=qs.filter(q=>latest(q.id)).length,correct=qs.filter(q=>latest(q.id)?.good).length,strong=card.querySelectorAll(".result-summary strong")[0];if(strong)strong.textContent=`進捗 ${done}/${qs.length}問実施・${correct}/${qs.length}問正解`});const weekAgo=Date.now()-7*86400000,attempts=[...new Set(data.results.filter(r=>new Date(r.at).getTime()>=weekAgo).map(r=>r.attempt))].map(id=>data.results.filter(r=>r.attempt===id)).sort((a,b)=>b[0].at.localeCompare(a[0].at));document.querySelectorAll("[data-toggle-attempt]").forEach((b,i)=>{if(b.parentElement.querySelector(".reset-attempt"))return;const reset=document.createElement("button");reset.className="tiny danger reset-attempt";reset.textContent="リセット（削除）";reset.onclick=()=>{const id=attempts[i]?.[0]?.attempt;if(!id||!confirm("この鍛錬履歴を削除しますか？"))return;data.results=data.results.filter(r=>r.attempt!==id);localStorage.setItem(KEY,JSON.stringify(data));render();renderHistory()};b.after(reset)})}
 const oldHistory=renderHistory;renderHistory=function(){oldHistory();enhanceParentResults()};renderHistory();
}
})();
